---
- name: Load values-global.yaml
  ansible.builtin.import_playbook: ./load_values_global.yml

- name: Determine secrets backing store
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    pattern_dir: "."
  tasks:
    - name: Set fact for secretStore backend
      ansible.builtin.set_fact:
        secrets_backing_store: "{{ values_global.global.secretStore.backend | default('vault') }}"
