---
- name: Determine pattern directory
  ansible.builtin.import_playbook: ./determine_pattern_dir.yml

- name: Determine pattern name
  ansible.builtin.import_playbook: ./determine_pattern_name.yml

- name: Load values-global.yaml for secrets store
  ansible.builtin.import_playbook: ./load_values_global.yml

- name: Determine secrets store backend
  ansible.builtin.import_playbook: ./determine_secretstore_backend.yml

- name: Parse and display secrets
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    hide_sensitive_output: false
  tasks:
    # Set the VALUES_SECRET environment variable to the file to parse
    - name: Find and decrypt secrets if needed
      ansible.builtin.include_role:
        name: find_vp_secrets

    # find_vp_secrets will return a plaintext data structure called values_secrets_data
    # This will allow us to determine schema version and which backend to use
    - name: Determine how to load secrets
      ansible.builtin.set_fact:
        secrets_yaml: '{{ values_secrets_data | from_yaml }}'

    - name: Parse secrets data
      no_log: '{{ hide_sensitive_output }}'
      parse_secrets_info:
        values_secrets_plaintext: "{{ values_secrets_data }}"
        secrets_backing_store: "{{ secrets_backing_store }}"
      register: secrets_results

    - name: Display secrets data
      ansible.builtin.debug:
        var: secrets_results
