---
- name: Load values-global.yaml
  ansible.builtin.import_playbook: ./load_values_global.yml

- name: Set secrets backend
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    desired_secrets_backend: "vault"
    yq_file: "{{ pattern_dir }}/values-global.yaml"
  tasks:
    - name: Script yq to set secrets backend
      ansible.builtin.command:
        cmd: |
          yq -i '.global.secretStore.backend = "{{ desired_secrets_backend }}"' {{ yq_file }}
