---
name: Ansible collection sanity tests

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

on: [push, pull_request]

jobs:
  ansible_unittests:
    name: Ansible collection sanity tests
    strategy:
      matrix:
        python-version: [3.11.3, 3.12.6]
        ansible-core: ["2.16.*"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: ansible_collections/rhvp/cluster_utils

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest ansible-core=='${{ matrix.ansible-core }}'

      - name: Run make ansible-sanitytest
        run: |
          cd ansible_collections/rhvp/cluster_utils
          make ansible-sanitytest
